package edu.nyu.cs.fb1258.string_examples.counting_occurrences;

/**
 * Try out the OccurenceCounter class.
 * @author Foo Barstein
 * @version 2
 *
 */

public class TestOccurrenceCounter {
	
	public static void main(String[] args) {
	    //corporate jargon text generated by bullshitipsum.com
		String myText = "Synergies platforms  visualize e-business cross-media platforms  addelivery communities synergies, e-commerce  infrastructures, tagclouds. Turn-key web- readiness folksonomies enable out-of-the-box  efficient relationships, ubiquitous,  bandwidth e-commerce A-list. Redefine  mindshare dynamic beta-test embrace,  platforms embedded value models reinvent  synergize. Architect leverage redefine  aggregate engage social e-commerce  relationships semantic, grow integrated  reinvent semantic citizen-media--productize  content efficient. Vortals productize,  reintermediate, blogospheres A-list e- enable; niches, rss-capable aggregate  virtual Cluetrain models efficient  envisioneer niches. Strategic utilize niches  action-items matrix, 24/7 transition deliver  global interfaces Cluetrain whiteboard  sticky! Cultivate authentic, A-list  integrate brand cultivate niches, Cluetrain  engineer e-business technologies, engineer  podcasting communities systems, syndicate  markets innovative schemas user-contributed,  enhance. Whiteboard embrace dynamic,  ubiquitous enhance solutions mesh  blogospheres, widgets. Initiatives  folksonomies engage robust portals, A-list  strategic extensible platforms action-items  web-readiness leading-edge; eyeballs  convergence synergies e-business tag  initiatives web services?";

		// determine number of occurrences of the word "platform" within this text
		String myWord = "platform";
		int number =  OccurrenceCounter.numberOfOccurrences(myWord, myText);

		// output the number of occurrences
		System.out.println("The word " + myWord + " is used " + number + " times.");
	}


}
